export const COMPRA_POKEMON = 'COMPRA_POKEMON';
export const DEVUELVE_POKEMON = 'DEVUELVE_POKEMON';

export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';